# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'Livvz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Giziku

  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'


  pod 'Firebase/AdMob'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Crash'
  pod 'Firebase/Firestore'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    # Add any other subspecs you want to use in your project
  ]
  target 'LivvzTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Livvz-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Giziku-tvOS

end
