# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Giziku' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Giziku

  pod 'Firebase/Core'
  target 'GizikuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Giziku-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Giziku-tvOS

end
